--------------------------------------------------------
--  File created - пятница-марта-18-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence FIN_WHEEL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SYSADM1"."FIN_WHEEL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ROUGH_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SYSADM1"."ROUGH_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SYSADM1"."USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence WHEEL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SYSADM1"."WHEEL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 78 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table FINISHED_WHEEL
--------------------------------------------------------

  CREATE TABLE "SYSADM1"."FINISHED_WHEEL" 
   (	"ID_REC" NUMBER(*,0), 
    "REC_DATE" DATE, 
    "REC_WHEEL_ID" NUMBER(6,0), 
    "GODNOST" VARCHAR2(3 BYTE), 
    "ID_USER" NUMBER, 
    "DIAM_KRUGA_KATANIYA_NS" NUMBER(3,0), 
    "SHIRINA_OBODA_NS" NUMBER(5,1), 
    "UTOPANIE_NS" NUMBER(2,0), 
    "DIAM_STUPICI_NS" VARCHAR2(20 BYTE), 
    "VILET_STUPICI_VS" NUMBER(2,0), 
    "TOLSHINA_DISKA_U_OBODA_VS" NUMBER(2,0), 
    "TOLSHINA_DISKA_U_STUPICI_VS" NUMBER(2,0), 
    "TOLSHINA_DISKA_V_SEREDINE_VS" NUMBER(2,0), 
    "VNUTRENNIY_DIAM_OBODA" NUMBER(3,0), 
    "DIAM_STUPICI_VS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROUGH_DATA
--------------------------------------------------------

  CREATE TABLE "SYSADM1"."ROUGH_DATA" 
   (	"REC_ID" NUMBER(6,0), 
    "REC_DATE" DATE, 
    "REC_USER" VARCHAR2(100 CHAR), 
    "ID_WHEEL" NUMBER(6,0), 
    "YEAR_WHEEL" NUMBER(2,0), 
    "ID_MELT" NUMBER(8,0), 
    "YEAR_MELT" NUMBER(2,0), 
    "GODNOST" VARCHAR2(5 BYTE), 
    "KALIBROVKA" NUMBER(2,0), 
    "RASTOCHKA" NUMBER(2,0), 
    "DIAMETR_KRUGA_KATANIYA" NUMBER(3,0), 
    "SHIRINA_OBODA" NUMBER(5,1), 
    "UTOPANIE_STUPICI" NUMBER(2,0), 
    "PRICHINA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "SYSADM1"."USERS" 
   (	"USER_ID" NUMBER(*,0), 
    "TABELNIY_NOMER" NUMBER(6,0), 
    "PASSWORD" VARCHAR2(20 BYTE), 
    "FIO" VARCHAR2(25 BYTE), 
    "SMENA" VARCHAR2(1 BYTE), 
    "LOGIN" VARCHAR2(20 BYTE), 
    "ID_STANKA" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table WHEEL
--------------------------------------------------------

  CREATE TABLE "SYSADM1"."WHEEL" 
   (	"ID_REC_WHEEL" NUMBER(*,0), 
    "ID_REC" NUMBER(*,0), 
    "ID_OPER" VARCHAR2(10 BYTE), 
    "GODNOST" VARCHAR2(5 BYTE), 
    "ID_USER" NUMBER, 
    "REC_DATE" VARCHAR2(50 BYTE), 
    "DIAM_KRUGA_KATANIYA_NS" NUMBER(3,0), 
    "SHIRINA_OBODA_NS" NUMBER(5,1), 
    "UTOPANIE_NS" NUMBER(2,0), 
    "DIAM_STUPICI_NS" VARCHAR2(1 BYTE), 
    "VILET_STUPICI_VS" NUMBER(2,0), 
    "TOLSHINA_DISKA_U_OBODA_VS" NUMBER(2,0), 
    "TOLSHINA_DISKA_U_STUPICI_VS" NUMBER(2,0), 
    "TOLSHINA_DISKA_V_SEREDINE_VS" NUMBER(2,0), 
    "VNUTRENNIY_DIAM_OBODA_VS" NUMBER(3,0), 
    "DIAM_STUPICI_VS" VARCHAR2(1 BYTE), 
    "PROFIL" VARCHAR2(1 BYTE), 
    "PRICHINA_BRAKA" VARCHAR2(30 BYTE), 
    "MARKIROVKA" VARCHAR2(20 BYTE), 
    "VIYAVLENNIY_DEFEKT" VARCHAR2(25 BYTE), 
    "VNUTRENNIY_DIAM_OBODA_NS" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSADM1.FINISHED_WHEEL
SET DEFINE OFF;
REM INSERTING into SYSADM1.ROUGH_DATA
SET DEFINE OFF;
Insert into SYSADM1.ROUGH_DATA (REC_ID,REC_DATE,REC_USER,ID_WHEEL,YEAR_WHEEL,ID_MELT,YEAR_MELT,GODNOST,KALIBROVKA,RASTOCHKA,DIAMETR_KRUGA_KATANIYA,SHIRINA_OBODA,UTOPANIE_STUPICI,PRICHINA) values ('0',to_date('02.02.16','DD.MM.RR'),'Petrov','1','16','1','16','Т','12','22','930','143,3','40',null);
Insert into SYSADM1.ROUGH_DATA (REC_ID,REC_DATE,REC_USER,ID_WHEEL,YEAR_WHEEL,ID_MELT,YEAR_MELT,GODNOST,KALIBROVKA,RASTOCHKA,DIAMETR_KRUGA_KATANIYA,SHIRINA_OBODA,UTOPANIE_STUPICI,PRICHINA) values ('1',to_date('02.02.16','DD.MM.RR'),'Ivanov','2','16','2','16','П','13','25','830','140,1','24','Ут.ст.н.с');
Insert into SYSADM1.ROUGH_DATA (REC_ID,REC_DATE,REC_USER,ID_WHEEL,YEAR_WHEEL,ID_MELT,YEAR_MELT,GODNOST,KALIBROVKA,RASTOCHKA,DIAMETR_KRUGA_KATANIYA,SHIRINA_OBODA,UTOPANIE_STUPICI,PRICHINA) values ('2',to_date('03.02.16','DD.MM.RR'),'Remontov','3','16','3','16','Р','25','25','950','128,4','23','Ут.ст.н.с');
Insert into SYSADM1.ROUGH_DATA (REC_ID,REC_DATE,REC_USER,ID_WHEEL,YEAR_WHEEL,ID_MELT,YEAR_MELT,GODNOST,KALIBROVKA,RASTOCHKA,DIAMETR_KRUGA_KATANIYA,SHIRINA_OBODA,UTOPANIE_STUPICI,PRICHINA) values ('3',to_date('03.02.16','DD.MM.RR'),'Brakov','444444','16','444444','16','Б-к','12','23','930','123,5','24',null);
REM INSERTING into SYSADM1.USERS
SET DEFINE OFF;
Insert into SYSADM1.USERS (USER_ID,TABELNIY_NOMER,PASSWORD,FIO,SMENA,LOGIN,ID_STANKA) values ('0','666666','1234','Tocarev V.S.','A','1111','1a №1');
REM INSERTING into SYSADM1.WHEEL
SET DEFINE OFF;
Insert into SYSADM1.WHEEL (ID_REC_WHEEL,ID_REC,ID_OPER,GODNOST,ID_USER,REC_DATE,DIAM_KRUGA_KATANIYA_NS,SHIRINA_OBODA_NS,UTOPANIE_NS,DIAM_STUPICI_NS,VILET_STUPICI_VS,TOLSHINA_DISKA_U_OBODA_VS,TOLSHINA_DISKA_U_STUPICI_VS,TOLSHINA_DISKA_V_SEREDINE_VS,VNUTRENNIY_DIAM_OBODA_VS,DIAM_STUPICI_VS,PROFIL,PRICHINA_BRAKA,MARKIROVKA,VIYAVLENNIY_DEFEKT,VNUTRENNIY_DIAM_OBODA_NS) values ('60','1','3','Б-к','0','18.03.2016 12:28:54','232','213,5',null,null,null,null,null,null,null,null,'1','Вм.я.ст.в.с',null,null,null);
Insert into SYSADM1.WHEEL (ID_REC_WHEEL,ID_REC,ID_OPER,GODNOST,ID_USER,REC_DATE,DIAM_KRUGA_KATANIYA_NS,SHIRINA_OBODA_NS,UTOPANIE_NS,DIAM_STUPICI_NS,VILET_STUPICI_VS,TOLSHINA_DISKA_U_OBODA_VS,TOLSHINA_DISKA_U_STUPICI_VS,TOLSHINA_DISKA_V_SEREDINE_VS,VNUTRENNIY_DIAM_OBODA_VS,DIAM_STUPICI_VS,PROFIL,PRICHINA_BRAKA,MARKIROVKA,VIYAVLENNIY_DEFEKT,VNUTRENNIY_DIAM_OBODA_NS) values ('58','0','1','Т','0','18.03.2016 12:23:33','928','142,1','38','1',null,null,null,null,null,null,null,null,null,null,'805');
Insert into SYSADM1.WHEEL (ID_REC_WHEEL,ID_REC,ID_OPER,GODNOST,ID_USER,REC_DATE,DIAM_KRUGA_KATANIYA_NS,SHIRINA_OBODA_NS,UTOPANIE_NS,DIAM_STUPICI_NS,VILET_STUPICI_VS,TOLSHINA_DISKA_U_OBODA_VS,TOLSHINA_DISKA_U_STUPICI_VS,TOLSHINA_DISKA_V_SEREDINE_VS,VNUTRENNIY_DIAM_OBODA_VS,DIAM_STUPICI_VS,PROFIL,PRICHINA_BRAKA,MARKIROVKA,VIYAVLENNIY_DEFEKT,VNUTRENNIY_DIAM_OBODA_NS) values ('59','0','2','Т','0','18.03.2016 12:26:37',null,null,null,null,'21','23','32','53','806',null,null,null,null,null,null);
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSADM1"."USERS_PK" ON "SYSADM1"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index WHEEL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSADM1"."WHEEL_PK" ON "SYSADM1"."WHEEL" ("ID_REC_WHEEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ROUGH_DATA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSADM1"."ROUGH_DATA_PK" ON "SYSADM1"."ROUGH_DATA" ("REC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FINISHED_WHEEL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSADM1"."FINISHED_WHEEL_PK" ON "SYSADM1"."FINISHED_WHEEL" ("ID_REC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "SYSADM1"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSADM1"."USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table WHEEL
--------------------------------------------------------

  ALTER TABLE "SYSADM1"."WHEEL" ADD CONSTRAINT "WHEEL_PK" PRIMARY KEY ("ID_REC_WHEEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSADM1"."WHEEL" MODIFY ("ID_REC_WHEEL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FINISHED_WHEEL
--------------------------------------------------------

  ALTER TABLE "SYSADM1"."FINISHED_WHEEL" ADD CONSTRAINT "FINISHED_WHEEL_PK" PRIMARY KEY ("ID_REC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSADM1"."FINISHED_WHEEL" MODIFY ("ID_REC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROUGH_DATA
--------------------------------------------------------

  ALTER TABLE "SYSADM1"."ROUGH_DATA" ADD CONSTRAINT "ROUGH_DATA_PK" PRIMARY KEY ("REC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSADM1"."ROUGH_DATA" MODIFY ("YEAR_MELT" NOT NULL ENABLE);
  ALTER TABLE "SYSADM1"."ROUGH_DATA" MODIFY ("ID_MELT" NOT NULL ENABLE);
  ALTER TABLE "SYSADM1"."ROUGH_DATA" MODIFY ("YEAR_WHEEL" NOT NULL ENABLE);
  ALTER TABLE "SYSADM1"."ROUGH_DATA" MODIFY ("ID_WHEEL" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FINISHED_WHEEL
--------------------------------------------------------

  ALTER TABLE "SYSADM1"."FINISHED_WHEEL" ADD CONSTRAINT "FINISHED_WHEEL_FK1" FOREIGN KEY ("ID_USER")
      REFERENCES "SYSADM1"."USERS" ("USER_ID") ENABLE;
  ALTER TABLE "SYSADM1"."FINISHED_WHEEL" ADD CONSTRAINT "FINISHED_WHEEL_FK2" FOREIGN KEY ("REC_WHEEL_ID")
      REFERENCES "SYSADM1"."ROUGH_DATA" ("REC_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WHEEL
--------------------------------------------------------

  ALTER TABLE "SYSADM1"."WHEEL" ADD CONSTRAINT "WHEEL_FK1" FOREIGN KEY ("ID_USER")
      REFERENCES "SYSADM1"."USERS" ("USER_ID") ENABLE;
  ALTER TABLE "SYSADM1"."WHEEL" ADD CONSTRAINT "WHEEL_FK2" FOREIGN KEY ("ID_REC")
      REFERENCES "SYSADM1"."ROUGH_DATA" ("REC_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger FIN_WHEEL_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSADM1"."FIN_WHEEL_ID_TRG" 
before insert on FINISHED_WHEEL
for each row
begin
  if :new.id_rec is null then
    select fin_wheel_seq.nextval into :new.id_rec from dual;
  end if;
end;
/
ALTER TRIGGER "SYSADM1"."FIN_WHEEL_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ROUGH_REC_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSADM1"."ROUGH_REC_ID_TRG" 
before insert on ROUGH_DATA
for each row
begin
  if :new.rec_id is null then
    select rough_seq.nextval into :new.rec_id from dual;
  end if;
end;
/
ALTER TRIGGER "SYSADM1"."ROUGH_REC_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USERS_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSADM1"."USERS_ID_TRG" 
before insert on users
for each row
begin
  if :new.user_id is null then
    select users_seq.nextval into :new.user_id from dual;
  end if;
end;
/
ALTER TRIGGER "SYSADM1"."USERS_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger WHEEL_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSADM1"."WHEEL_ID_TRG" 
before insert on WHEEL
for each row
begin
  if :new.id_rec_wheel is null then
    select wheel_seq.nextval into :new.id_rec_wheel from dual;
  end if;
end;
/
ALTER TRIGGER "SYSADM1"."WHEEL_ID_TRG" ENABLE;
